name: Clean, Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches:
      - main
      - develop

jobs:
  commit-build:
    name: ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          # os: used for the runner
          # platform: a generic platform name
          # target: used by Cargo
          # arch: either 386, arm64 or amd64
          - os: ubuntu-latest
            platform: linux
            target: x86_64-unknown-linux-gnu
            arch: amd64
          # - os: ubuntu-latest
          #   platform: linux
          #   target: aarch64-unknown-linux-gnu
          #   arch: arm64
          - os: macos-latest
            platform: darwin
            target: x86_64-apple-darwin
            arch: amd64
          - os: macos-latest
            platform: darwin
            target: aarch64-apple-darwin
            arch: arm64
          - os: windows-latest
            platform: win32
            target: x86_64-pc-windows-msvc
            arch: amd64
          - os: windows-latest
            platform: win32
            target: aarch64-pc-windows-msvc
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -PskipSigning=true --stacktrace
