name: Clean, Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  commit-build:
    strategy:
      fail-fast: false
      matrix:
        # a list of all the targets
        include:
          - OS: ubuntu-20.04
          - OS: macos-latest
          - OS: windows-latest
    runs-on: ${{ matrix.OS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for download_libs.sh
        run: chmod +x download_libs.sh
      - name: Download libs
        run: sh download_libs.sh
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -PskipSigning=true --stacktrace
